---
title: "July Effect - Preliminary"
author: "Mustafa Ascha"
date: "January 25, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
library(pander)
library(tidyverse)
library(mice)

devtools::document()
#devtools::build()
devtools::load_all()

otl <- outcomes_list <- list()
otl[["everyone"]] <- paste0(c("returnor", "supinfec"), "_01")
otl[["cosmetics"]] <- paste0(c("returnor", "supinfec"), "_01")
otl[["no_cosmetic"]] <- paste0(c("returnor", "supinfec"), "_01")

```


```{r read data}
nsqip <- map(c("everyone", "cosmetics", "no cosmetics"), make_je_nsqip) 
names(nsqip) <- c("everyone", "cosmetics", "no_cosmetic")
```

```{r make table ones}
#tbl_ones_pgy <- map(nsqip, tbl_one, strat = "pgy_bin")
tbl_ones <- map(nsqip, tbl_one, strat = "admqtr")

suppress_infrequent_p <- function(tbl_one){
  to_suppress <- apply(tbl_one[,1:2], 1, function(x) any(x <= 5))
  tbl_one[to_suppress,3] <- NA
  tbl_one
}

```

```{r setup propensity score dataframe, results = 'hide'}

nsqip <- nsqip %>% map(function(df){
  preds <- nsqipr::paper_stuff$mona$predictors
  the_form <- paste0("pgy01 ~ ", paste0(preds, collapse = " + "))
  df[["propensity_score"]] <-
    predict(glm(the_form, "binomial", df), df, type = "response")
  df
})

paper_stuff$mona[["predictors"]] <-
   c(nsqipr::paper_stuff$mona[["predictors"]], "propensity_score")

nsqip <- nsqip %>% map(binarize_outcomes)
#check which variables are cool
#map(nsqip, function(x) map(x[paper_stuff$mona$outcomes], table))

nsqip <- map(nsqip, model_vars)
pscores <- map(nsqip, 2)
nsqip <- map(nsqip, 1)

impute_fn <- function(df) mice(df, m=1, maxit=50, seed=400, ridge=0.01)
nsqip <- map(nsqip, function(df) mice::complete(impute_fn(df), 1))
nsqip <- map2(nsqip, pscores, function(x, y) na.omit(bind_cols(x, y)))

matched_data <- map(nsqip, match_fn)
unmatched_data <- nsqip

#match_fn(nsqip[[1]])
```


```{r model and tidy models, results = 'hide'}

glms <- do_glms(matched_data, unmatched_data)

tidied_models <-
  map2(glms, names(glms),
       function(dflist, dfnm) {
         map(dflist, function(mdl) {
           mutate(broom::tidy(mdl[[1]]), glm = dfnm, outcome = mdl[[2]])
             })
         }) %>% 
  flatten_dfr


confint_models <-
  map2(glms, names(glms),
       function(dflist, dfnm) {
         map(dflist, function(mdl) {
           cbind(confint(mdl[[1]]), glm = dfnm, outcome = mdl[[2]])
           })
         }) %>% 
  flatten_matrices_df


models_df <- full_join(tidied_models, confint_models)
models_df <-
  models_df[,!grepl("1$", names(models_df))] %>%
  select(-statistic, -std.error)

to_exp <- c("estimate", "conf.lower", "conf.upper")
models_df[,to_exp] <- lapply(models_df[,to_exp], function(x) {
  sprintf("%.4f", exp(as.numeric(x)))})

for_show <- c("term", "glm", "outcome", "estimate", "conf.lower", "conf.upper", "p.value")
models_df <- models_df[,for_show]
models_df$outcome <- gsub("_01$", "", models_df$outcome)

models_df <- models_df %>% 
  filter(!(term %in% c("(Intercept)", "propensity_score"))) 
#                       "admqtr3", "pgy_binThree or lower")))

models_df$propensity <- 
  ifelse(grepl("no_prop", models_df$glm), "Unmatched", "Matched")

models_df$population <- gsub("no_prop_", "", models_df$glm)
models_df$population <- gsub("_", " ", models_df$population)

to_replace <- 
  c("admqtr2", "admqtr3", 
    "pgy_binFour or above", "pgy_binThree\\ or\\ lower")
replacements <- c("Q2", "Q3", "PGY4+", "PGY3-")

models_df$term <- 
  reduce2(to_replace, replacements, 
          function(innit, tr, rep) gsub(tr, rep, innit), 
          .init = models_df$term)

fxr_uppers <- 
  with(models_df, as.numeric(estimate) == 0 |
                 as.numeric(conf.upper) > 10 |   
                 is.na(conf.lower))
fxr_uppers <- ifelse(is.na(fxr_uppers), TRUE, fxr_uppers)

models_df[fxr_uppers,c("estimate", "conf.lower", "conf.upper", "p.value")] <- 
  NA

to_show <- 
  c("term", "population", "propensity", "outcome", 
    "estimate", "conf.lower", "conf.upper", "p.value")

models_df <- models_df[,to_show]

```

# Table ones

## Whole Population

```{r}
pander(tbl_ones[[1]][,1:3])
```


## Cosmetics procedures

```{r}
pander(tbl_ones[[2]][,1:3])
```


## Non-cosmetics procedures

```{r}
pander(tbl_ones[[3]][,1:3])
```

\pagebreak 

# Odds of outcome during 3rd quarter

Here, we are looking at an estimate of the odds ratio of an outcome for the third quarter compared to the second quarter, PGY3 and below versus PGY4 and above, and the interaction between those two.  

```{r}
pander(models_df %>% filter(term == "Q3") %>% arrange(desc(outcome, propensity)), split.table = Inf)
```

```{r}
pander(models_df %>% filter(term != "Q3") %>% arrange(desc(outcome, propensity)), split.table = Inf)
```


# Propensity score visualization 

```{r}

propplot <- function(df) ggplot(df, aes(propensity_score, fill = admqtr)) + geom_histogram()

map(nsqip, propplot)

```










